---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'materialize'

Estimate:
  api_access: true

---
Name: seeder
---

Seeder:
  providers:
    - Seeder

Seeder\Seeder:
    create:
        -
            key: Role1
            class: Role
            fields:
                Name: Quality Engineer
        -
            key: Role2
            class: Role
            fields:
                Name: Applications Engineer
        -
            key: Role3
            class: Role
            fields:
                Name: Front-end Engineer
        -
            key: Role4
            class: Role
            fields:
                Name: Production Engineer
        -
            key: Role5
            class: Role
            fields:
                Name: eCommerce Solutions
        -
            key: Role6
            class: Role
            fields:
                Name: Project Management
        -
            key: Role7
            class: Role
            fields:
                Name: Client Success
        -
            key: Role8
            class: Role
            fields:
                Name: Optimization Strategy
        -
            key: RiskType1
            class: RiskType
            fields:
                Name: Budget
        -
            key: RiskType2
            class: RiskType
            fields:
                Name: Schedule
        -
            key: RiskType3
            class: RiskType
            fields:
                Name: Quality
        -
            key: Platform1
            class: Platform
            fields:
                Name: Magento 1
        -
            key: Platform2
            class: Platform
            fields:
                Name: Magento 2
        -
            key: Platform3
            class: Platform
            fields:
                Name: Sales Force Commerce Cloud
        Skill:
            count: 30
            fields:
                Name: Seeder(skill)
        Category:
            count: 25
            fields:
                Name: Seeder(category)
        LineItem:
            count: 100
            fields:
                Description: faker(sentence, 6)
                NumHours: faker(numberBetween, 2, 10)
                Skills: random(Skill)
                Roles: random(Role)
        Story:
            count: 10
            fields:
                Name: faker(sentence, 6)
                LineItems: random(LineItem, 4)
        Risk:
            count: 5
            fields:
                Name: Seeder(risk)
                Description: faker(paragraphs, 3, true)
                MitigationPlan: faker(sentence, 10)
                MitigationCost: faker(numberBetween, 1, 10)
                PotentialCost: faker(numberBetween, 1, 10)
                RiskTypes: random(RiskType)
                Probability: 2
        Client:
            count: 10
            fields:
                Name: faker(company)
                Code: faker(lexify, '???')
        Estimate:
            count: 100
            fields:
                Name: Seeder(name)
                Description: faker(sentence, 10)
                BusinessRequirements: faker(paragraphs, 3, true)
                FunctionialRequirements: faker(paragraphs, 3, true)
                TechnicalApproach: faker(paragraphs, 3, true)
                RomLow: Seeder(romLow)
                RomHigh: Seeder(romHigh)
                BudgetConfidence: High
                ScheduleConfidence: Medium
                TechnicalConfidence: Low
                Risks: random(Risk, 3)
                Categorys: random(Category, 3)
                Clients: random(Client, 2)
                Stories: random(Story, 3)
                Platforms: random(Platform, 1)
