---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

---
Name: seeder
---

Seeder\Seeder:
    create:
        -
            key: Role1
            class: Role
            fields:
                Name: Quality Engineer
        -
            key: Role1
            class: Role
            fields:
                Name: Applications Engineer
        -
            key: Role1
            class: Role
            fields:
                Name: Frontend Engineer
        -
            key: RiskType1
            class: RiskType
            fields:
                Name: Budget
        -
            key: RiskType2
            class: RiskType
            fields:
                Name: Schedule
        -
            key: RiskType3
            class: RiskType
            fields:
                Name: Quality
        Skill:
            count: 10
            fields:
                Name: faker(jobTitle)
        Platform:
            count: 10
            fields:
                Name: faker(company)
        LineItem:
            count: 10
            fields:
                Description: faker(sentence, 6)
                NumHours: faker(numberBetween, 2, 10)
        Story:
            count: 10
            fields:
                Name: faker(sentence, 6)
                LineItems: random(LineItem, 10)
        Risk:
            count: 10
            fields:
                Name: faker(sentence, 6)
                Description: faker(paragraphs, 3, true)
                MitigationPlan: faker(sentence, 10)
                MitigationCost: faker(numberBetween, 1, 10)
                PotentialCost: faker(numberBetween, 1, 10)
                RiskTypes: random(RiskType)
                Probability: 2
